kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata: 
  name: devopsbatches.trainwithnetra.com
spec:
  group: trainwithnetra.com
  names:
    plural: devopsbatches
    singular: devopsbatch
    kind: DevopsBatch
    shortNames: 
      - net
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "this is the name of devops batch"
              duration:
                type: string
                description: "this is the duration of the devops batch"
              mode:
                type: string
                description: "this is the mode of the batch"
              platform:
                type: string
                description: "this is the platform of batch"    
        

            
